1)Create a NumPy array of integers from 1 to 10.



In [3]:
import numpy as np

In [57]:
arr1 = np.arange(1,11)

In [58]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

2)Create a 2x3 NumPy array filled with zeros.

In [59]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

3)Create a NumPy array of even numbers from 2 to 20.

In [60]:
arr2 = np.arange(2,21,2)
arr2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

4)Given two NumPy arrays, arr1 = np.array([1, 2, 3]) and arr2 = np.array([4,
5, 6]), perform element-wise addition, subtraction, multiplication, and
division between the two arrays.

In [61]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

In [62]:
# Addition
A = arr1 + arr2
A

array([5, 7, 9])

In [63]:
#Subtraction
s = arr1 - arr2
s

array([-3, -3, -3])

In [64]:
#Multiplication
m = arr1*arr2
m

array([ 4, 10, 18])

In [65]:
#Division
d = arr2/arr1
d

array([4. , 2.5, 2. ])

5)Compute the mean, median, and standard deviation of a NumPy array
containing 100 random numbers.

In [66]:
arr = np.random.randint(0,100,100)
arr

array([96,  5, 52, 29, 14, 27, 95, 54, 71, 56, 34, 12, 88, 17, 26, 53, 46,
       50, 52, 96, 74, 34, 98, 22, 51, 60, 30, 66,  8, 74, 57, 27, 13, 20,
       72, 40, 36, 85, 40, 23, 49, 84, 61, 87, 67,  1, 22, 61, 95,  2, 54,
       48, 59, 71, 86, 48, 73, 44, 69,  7, 61, 18, 76, 48, 57, 55, 78, 18,
       36, 26,  6, 71, 96, 69, 57, 21, 38,  2, 32, 97, 62,  1, 50, 17, 11,
       53, 82, 95, 70, 58, 75,  0,  8, 10, 71, 33, 91, 67, 24, 32])

In [67]:
#Mean
arr.mean()

48.63

In [68]:
#Median
np.median(arr)

51.5

In [69]:
#Standard Deviation
np.std(arr)

27.86598464077665

6)Reshape a 1D NumPy array of 12 random elements into a 2D array with a
shape of (3, 4).

In [70]:
arr = np.random.randint(1,100,12)
arr

array([34, 27, 46, 74, 40, 59, 49, 52, 10, 22, 98, 55])

In [71]:
arr.reshape(3,4)

array([[34, 27, 46, 74],
       [40, 59, 49, 52],
       [10, 22, 98, 55]])

 7)Given a NumPy array arr = np.array([1, 2, 3, 4, 5]), square each element in
the array using NumPy functions

In [72]:
arr = np.array([1,2,3,4,5])
np.square(arr)

array([ 1,  4,  9, 16, 25])

8) Create a 5x5 identity matrix using NumPy.


In [73]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

9)Calculate the dot product of two NumPy arrays, a = np.array([1, 2, 3]) and
b = np.array([4, 5, 6]

In [7]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.dot(a,b)

32

10.Find the index of the maximum value and the index of the minimum value
in a NumPy array.

In [4]:
arr2 = np.random.randint(1,50,20)
arr2

array([28, 17,  6, 18, 20, 27, 26, 33, 35, 24, 49, 41, 22, 35, 20, 44, 30,
       15, 13, 33])

In [5]:
#Index of maximum value
arr2.argmax()

10

In [6]:
#Index of minimum value
arr2.argmin()

2

11.Concatenate two random NumPy arrays horizontally and vertically.

In [12]:
p = np.array([[1,2,3],[7,8,9]])
q = np.array([[4,5,6],[10,11,12]])

In [13]:
np.concatenate((p,q),axis=0)

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [ 4,  5,  6],
       [10, 11, 12]])

In [14]:
np.concatenate((p,q),axis=1)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

12.Given a 2D NumPy array, calculate the sum of each row and each column separately.

In [16]:
p = np.array([[1,2,3],[7,8,9]])
np.sum(p,axis = 0)

array([ 8, 10, 12])

In [17]:
np.sum(p,axis = 1)

array([ 6, 24])

13.Find the common elements between two NumPy arrays.

In [21]:
a7 = np.array([[1,2,3],[7,8,11]])
a8 = np.array([[1,3,3],[10,11,12]])

In [22]:
np.intersect1d(a7,a8)

array([ 1,  3, 11])

14.Replace all negative values in a NumPy array with zeros.

In [25]:
arr3 = np.array([-1,2,-3,4,-5,6])
arr3[arr3<0]=0
arr3

array([0, 2, 0, 4, 0, 6])

15.Create a NumPy array with random integers between 1 and 100 and then sort it in ascending order.

In [27]:
arr4 = np.random.randint(1,100,100)
arr4

array([46, 18, 17, 73, 39, 31, 33, 41, 93, 39,  4, 42, 13, 22, 66, 89, 13,
       27,  8, 24, 75, 37, 11, 84, 55, 29, 37,  8, 51, 38, 65, 51, 37, 10,
       98, 48, 25, 19, 36, 52,  7, 55, 67, 11, 87, 36, 45, 89, 21, 62, 21,
       39, 58, 65, 81, 20, 57, 39, 31, 35, 66, 43, 22, 83, 21, 24, 83, 56,
       94, 33, 10, 49, 66, 30, 99, 13, 95, 15, 13, 16, 85, 68,  2, 78, 62,
       96, 36, 69, 45, 32, 82, 51, 39, 20, 24, 35, 22, 81, 32, 65])

In [29]:
arr4.sort()
arr4

array([ 2,  4,  7,  8,  8, 10, 10, 11, 11, 13, 13, 13, 13, 15, 16, 17, 18,
       19, 20, 20, 21, 21, 21, 22, 22, 22, 24, 24, 24, 25, 27, 29, 30, 31,
       31, 32, 32, 33, 33, 35, 35, 36, 36, 36, 37, 37, 37, 38, 39, 39, 39,
       39, 39, 41, 42, 43, 45, 45, 46, 48, 49, 51, 51, 51, 52, 55, 55, 56,
       57, 58, 62, 62, 65, 65, 65, 66, 66, 66, 67, 68, 69, 73, 75, 78, 81,
       81, 82, 83, 83, 84, 85, 87, 89, 89, 93, 94, 95, 96, 98, 99])

16.Calculate the element-wise absolute difference between two NumPy arrays

In [30]:
a7 = np.array([[1,2,3],[7,8,11]])
a8 = np.array([[1,3,3],[10,11,12]])
x = np.absolute(np.array(a7)-np.array(a8))
x

array([[0, 1, 0],
       [3, 3, 1]])

17.Given a 2D NumPy array, extract the first row and the last column.

In [39]:
arr6 =np.array([[8, 12, 14], [15, 37, 25]])
arr6

array([[ 8, 12, 14],
       [15, 37, 25]])

In [40]:
arr6.ndim

2

In [74]:
#First Row
arr6[0:1]

array([[ 8, 12, 14]])

In [75]:
#Last column
arr6[0:2,[2]]

array([[14],
       [25]])

18.Slice a 1D NumPy array to get every other element

In [76]:
#a7 = np.array([[1,2,3],[7,8,11]])
a7[0:1,[0]]

array([[1]])

In [50]:
a7[0:1,[1]]

array([[2]])

In [48]:
a7[0:1,[2]]

array([[3]])

In [49]:
a7[1:2,[0]]

array([[7]])

In [51]:
a7[1:2,[1]]

array([[8]])

In [52]:
a7[1:2,[2]]

array([[11]])

19.Given a 2D NumPy array, extract a subarray consisting of the central 2x2 elements.

In [53]:
arr8 =np.array([[8, 12, 14], [15, 37, 25],[1,2,2]])
arr8

array([[ 8, 12, 14],
       [15, 37, 25],
       [ 1,  2,  2]])

In [55]:
arr8[0:2,[0,1]]

array([[ 8, 12],
       [15, 37]])

20.Reverse a 1D NumPy array using slicing.

In [56]:
#arr8 = array([[ 8, 12, 14],
       #[15, 37, 25],
       #[ 1,  2,  2]])
arr8[::-1]

array([[ 1,  2,  2],
       [15, 37, 25],
       [ 8, 12, 14]])